feat: add redirect in middleware for login/register if refresh token …
Dialosoft/frontend pull request #60
Opened 2024-08-17 21:38 UTC by Jaro-c

…is detected

# Pull Request

## Description

- Login and Register redirects

## Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

## Additional Information

Please add any other information that is important for this pull request.

2024-08-18 16:56 UTC, flavioramses approved these changes

2024-08-19 14:15 UTC, BustaGraphic requested changes
Bad developer

2024-08-19 14:16 UTC, Jaro-c commented
> Bad developer

Who?

2024-08-19 20:16 UTC, Jaro-c commented
done

2024-08-19 20:16 UTC, BustaGraphic approved these changes

2024-08-19 20:17 UTC, merged